### ISSUE TITLE
TODO: Tutorials

### ISSUE THREAD

**Issue by baggepinnen** [JuliaComputing/Multibody.jl#2]
- [x] Single and double pendulum (hello world)
    - https://juliacomputing.github.io/Multibody.jl/dev/examples/pendulum/
- [ ] Gantry-type 3DOF robot (think 3D printer)
- [ ] Stewart platform (modelica library exist that can be installed in OpenModelica). The modelica library uses a lot of nice features of modelica that aren't available in MTK/JSComp, such as
    - Composite parameter types (in MTK but not in JSComp)
    - Automatic generation of events upon `when`, used in inverse kinematics etc.
    - conditional defaults for parameters
    - final parameters and parameter propagation
- [x] 6DOF robot with revolute joints and flexible transmissions
    - Started in #29 
- [x] Four-bar linkage (kinematic loop)
    - https://github.com/JuliaComputing/Multibody.jl/pull/25 
- [x] Furuta pendulum
- [x] Quadrotor Primitive quad tutorial available at  https://github.com/JuliaComputing/Multibody.jl/blob/main/docs/src/examples/quad.md
    - [ ] wind model
    - [ ] battery consumption
- [ ] Some linear analysis tutorial with control design (JSComp lacks linearization https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/309) https://github.com/JuliaComputing/Multibody.jl/pull/114
- [ ] Kinematic calibration using markers
- [ ] Derive and generate kinematics functions
    - [x] Forward kinematics
    - [ ] Inverse kinematics https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/76
