### ISSUE TITLE
`@mtkmodel` meta issue

### ISSUE THREAD

**Issue by baggepinnen** [JuliaComputing/Multibody.jl#36]
The following is a list of issues with MTK that in some form or another leads to missing features or workarounds in Multibody.jl

- [ ] Array variables being almost totally broken (`collect` required everywhere)
- [x] https://github.com/SciML/ModelingToolkit.jl/issues/2322
    - [x] https://github.com/SciML/ModelingToolkit.jl/pull/2336
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2318
- [x] https://github.com/SciML/ModelingToolkit.jl/issues/2289
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2812
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2810
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2813
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2808
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2704
