### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by baggepinnen** [JuliaComputing/Multibody.jl#41]
The following list of issues should be addressed before a MWP of this package can be released
```[tasklist]
### Tasks
- [ ] https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/52
- [ ] https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/53
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2151
- [ ] #36 
- [ ] #39 
- [ ] https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/75
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2344
- [ ] https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/51
- [ ] https://github.com/JuliaComputing/JuliaSimCompiler.jl/issues/50
- [ ] https://github.com/SciML/ModelingToolkit.jl/issues/2000 (this issue hits Multibody models in particularly hard, since they have a strong tendency to produce dummy derivatives).
```

Multibody is making heavy use of arrays, and the fact that symbolic arrays they are so extraordinarily buggy is likely to lead to a rather poor user experience. Some of the issues above are directly tied to this. The fact that Multibody.jl contains (at the time of writing) about 250 calls to `collect`, including 28 occurrences in the tests, to workaround array bugs is an indication that users are likely to encounter the obscure error messages related to one of the numerous bugs that have been worked around by calling `collect` in the library.
