### ISSUE TITLE
Misc. TODO

### ISSUE THREAD

**Issue by baggepinnen** [JuliaComputing/Multibody.jl#71]
- [x] Shape files for BodyShape
- [ ] Length and width direction for BodyShape
- [x] Add feature tracing out a point in animations, e.g., tracing the path of the end effector in the robot example
- [x] Urdf import https://github.com/JuliaComputing/Multibody.jl/pull/143
